spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: your username
    password: your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 